### ISSUE TITLE
Bitalino read function

### ISSUE THREAD

**Issue by KReload** [andersoonluan/BITalino-Ionic#1]
Hi,

How can I use the read function of the BitalinoDevice class for Ionic ? There is no problem for the first argument (numberOfSamples). However for the second one (data), it is not clear what I need to fill.

Thank you

**Comment by andersoonluan** [comment]
Hello @KReload, thanks for your question!

The data is your return of Bluetooth Serial, for example:

` this.bluetoothSerial
  .subscribeRawData()
  .subscribe(
     (data) => {
         // this data you can use for call the method.
      }
  )`

If you have any question or problem for test the library, send me a e-mail to andersoonluan@gmail.com

Thanks!
